#pragma once

// Auto-generated by CMake -- do not edit
#define REXGLUE_VERSION_MAJOR 0
#define REXGLUE_VERSION_MINOR 10
#define REXGLUE_VERSION_PATCH 0
#define REXGLUE_VERSION_TWEAK 0
#define REXGLUE_VERSION_STRING "0.10.0.0-dev.unknown"
#define REXGLUE_VERSION_NUMERIC "0.10.0.0"
#define REXGLUE_VERSION_FLOOR "0.10.0"
#define REXGLUE_VERSION_CHANNEL "dev"

#define REXGLUE_BUILD_PLATFORM "android-arm64"
#define REXGLUE_BUILD_TIMESTAMP "20260927_1109"

// Requires REXGLUE_BUILD_CONFIG compile definition
// Title: "[rexglue-v0.7.5.38-dev.gb27f3f74-Release]"
#define REXGLUE_BUILD_TITLE \
  "[rexglue-v" REXGLUE_VERSION_STRING "-" REXGLUE_BUILD_CONFIG "]"

// Overlay: "build: rexglue-v0.7.5.38-dev.gb27f3f74-win-amd64-Release@20260420_1430"
#define REXGLUE_BUILD_STAMP \
  "build: rexglue-v" REXGLUE_VERSION_STRING "-" REXGLUE_BUILD_PLATFORM \
  "-" REXGLUE_BUILD_CONFIG "@" REXGLUE_BUILD_TIMESTAMP
