# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS rex::runtime rex::gpu-xenos rex::gpu-plume rex::disruptorplus rex::renderdoc rex::simde rex::tomlplusplus rex::aes128 rex::mspack rex::o1heap rex::disasm rex::xxhash rex::libavcodec rex::libavutil rex::SPIRV rex::glslang rex::MachineIndependent rex::GenericCodeGen rex::OSDependent rex::OGLCompiler rex::spirv-tools-headers rex::rexglue)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target rex::runtime
add_library(rex::runtime SHARED IMPORTED)

set_target_properties(rex::runtime PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<NOT:\$<CONFIG:Release>>:REXGLUE_ENABLE_PERF_COUNTERS>;REX_HAS_VULKAN=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "rex::simde;fmt::fmt;spdlog::spdlog;rex::tomlplusplus;android;Vulkan::Headers;GPUOpen::VulkanMemoryAllocator;rex::spirv-tools-headers"
)

# Create imported target rex::gpu-xenos
add_library(rex::gpu-xenos SHARED IMPORTED)

# Create imported target rex::gpu-plume
add_library(rex::gpu-plume SHARED IMPORTED)

# Create imported target rex::disruptorplus
add_library(rex::disruptorplus INTERFACE IMPORTED)

set_target_properties(rex::disruptorplus PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/disruptorplus"
)

# Create imported target rex::renderdoc
add_library(rex::renderdoc INTERFACE IMPORTED)

set_target_properties(rex::renderdoc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/renderdoc"
)

# Create imported target rex::simde
add_library(rex::simde INTERFACE IMPORTED)

set_target_properties(rex::simde PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target rex::tomlplusplus
add_library(rex::tomlplusplus INTERFACE IMPORTED)

set_target_properties(rex::tomlplusplus PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target rex::aes128
add_library(rex::aes128 STATIC IMPORTED)

set_target_properties(rex::aes128 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target rex::mspack
add_library(rex::mspack STATIC IMPORTED)

set_target_properties(rex::mspack PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target rex::o1heap
add_library(rex::o1heap STATIC IMPORTED)

set_target_properties(rex::o1heap PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target rex::disasm
add_library(rex::disasm STATIC IMPORTED)

set_target_properties(rex::disasm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target rex::xxhash
add_library(rex::xxhash STATIC IMPORTED)

set_target_properties(rex::xxhash PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/"
)

# Create imported target rex::libavcodec
add_library(rex::libavcodec STATIC IMPORTED)

set_target_properties(rex::libavcodec PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "rex::libavutil"
)

# Create imported target rex::libavutil
add_library(rex::libavutil STATIC IMPORTED)

set_target_properties(rex::libavutil PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target rex::SPIRV
add_library(rex::SPIRV STATIC IMPORTED)

set_target_properties(rex::SPIRV PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:rex::MachineIndependent>"
)

# Create imported target rex::glslang
add_library(rex::glslang STATIC IMPORTED)

set_target_properties(rex::glslang PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:rex::OGLCompiler>;\$<LINK_ONLY:rex::OSDependent>;\$<LINK_ONLY:rex::MachineIndependent>"
)

# Create imported target rex::MachineIndependent
add_library(rex::MachineIndependent STATIC IMPORTED)

set_target_properties(rex::MachineIndependent PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:rex::OGLCompiler>;\$<LINK_ONLY:rex::OSDependent>;\$<LINK_ONLY:rex::GenericCodeGen>"
)

# Create imported target rex::GenericCodeGen
add_library(rex::GenericCodeGen STATIC IMPORTED)

# Create imported target rex::OSDependent
add_library(rex::OSDependent STATIC IMPORTED)

set_target_properties(rex::OSDependent PROPERTIES
  INTERFACE_LINK_LIBRARIES "-pthread"
)

# Create imported target rex::OGLCompiler
add_library(rex::OGLCompiler STATIC IMPORTED)

# Create imported target rex::spirv-tools-headers
add_library(rex::spirv-tools-headers INTERFACE IMPORTED)

set_target_properties(rex::spirv-tools-headers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target rex::rexglue
add_executable(rex::rexglue IMPORTED)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/rexglueTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "fmt::fmt" "spdlog::spdlog" "Vulkan::Headers" "GPUOpen::VulkanMemoryAllocator" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
